name: Android CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "*" ]
jobs:
  # This workflow contains a single job called "build"
  build:

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Create google-services
      run: echo '${{ secrets.GOOGLE_SERVICES_JSON_DEBUG }}' > ./app/google-services.json
      
    # Build Debug App
    - name: Build with Gradle
      run: ./gradlew assembleDebug
      
    # Run unit test
    - name: Run unit test
      run: ./gradlew testdebugUnitTest
      
    - name: IA Android CI Discord Notification
      uses: sarisia/actions-status-discord@v1
      if: ${{ success() }}
      with:
        title: ✅ Idea Archieve Android CI success ✅
        webhook: ${{ secrets.ANDROID_DISCORD_WEBHOOK }}
        color: 00FF00

    - name: IA Android CI Discord Notification
      uses: sarisia/actions-status-discord@v1
      if: ${{ failure() }}
      with:
        title: ❗️ Idea Archieve Android CI failed ❗️
        webhook: ${{ secrets.ANDROID_DISCORD_WEBHOOK }}
        color: FF0000
